
#------------------------积分(目录)---------------------------
['积分']
menuId = 2000
icon = 'system'
path = 'integral'

#------------------------用户管理(二级菜单)---------------------------
['积分'.'用户管理']
menuId = 2001
icon = 'guid'
path = 'user_management'

#-----------积分->用户管理 按钮权限------------
['积分'.'用户管理'.'按钮权限'.'查询']
menuId = 2002
perms = 'query'

['积分'.'用户管理'.'按钮权限'.'添加']
menuId = 2003
perms = 'add'

['积分'.'用户管理'.'按钮权限'.'编辑']
menuId = 2004
perms = 'edit'

['积分'.'用户管理'.'按钮权限'.'删除']
menuId = 2005
perms = 'remove'

['积分'.'用户管理'.'按钮权限'.'导入']
menuId = 2006
perms = 'import'

['积分'.'用户管理'.'按钮权限'.'导出']
menuId = 2007
perms = 'export'

#------------------------增加管理(二级菜单)---------------------------
['积分'.'增加管理']
menuId = 2008
icon = 'guid'
path = 'increase_management'

#-----------积分->增加管理 按钮权限------------
['积分'.'增加管理'.'按钮权限'.'查询']
menuId = 2009
perms = 'query'

['积分'.'增加管理'.'按钮权限'.'添加']
menuId = 2010
perms = 'add'

['积分'.'增加管理'.'按钮权限'.'编辑']
menuId = 2011
perms = 'edit'

['积分'.'增加管理'.'按钮权限'.'删除']
menuId = 2012
perms = 'remove'

['积分'.'增加管理'.'按钮权限'.'导入']
menuId = 2013
perms = 'import'

['积分'.'增加管理'.'按钮权限'.'导出']
menuId = 2014
perms = 'export'

#------------------------积分计算配置(二级菜单)---------------------------
['积分'.'积分计算配置']
menuId = 2015
icon = 'guid'
path = 'integral_calculation_configuration'

#-----------积分->积分计算配置 按钮权限------------
['积分'.'积分计算配置'.'按钮权限'.'查询']
menuId = 2016
perms = 'query'

['积分'.'积分计算配置'.'按钮权限'.'添加']
menuId = 2017
perms = 'add'

['积分'.'积分计算配置'.'按钮权限'.'编辑']
menuId = 2018
perms = 'edit'

['积分'.'积分计算配置'.'按钮权限'.'删除']
menuId = 2019
perms = 'remove'

['积分'.'积分计算配置'.'按钮权限'.'导入']
menuId = 2020
perms = 'import'

['积分'.'积分计算配置'.'按钮权限'.'导出']
menuId = 2021
perms = 'export'

#------------------------VIP管理(目录)---------------------------
['VIP管理']
menuId = 2022
icon = 'system'
path = 'vip_management'

#------------------------VIP客户管理(二级菜单)---------------------------
['VIP管理'.'VIP客户管理']
menuId = 2023
icon = 'guid'
path = 'vip_customer_management'

#-----------VIP管理->VIP客户管理 按钮权限------------
['VIP管理'.'VIP客户管理'.'按钮权限'.'查询']
menuId = 2024
perms = 'query'

['VIP管理'.'VIP客户管理'.'按钮权限'.'添加']
menuId = 2025
perms = 'add'

['VIP管理'.'VIP客户管理'.'按钮权限'.'编辑']
menuId = 2026
perms = 'edit'

['VIP管理'.'VIP客户管理'.'按钮权限'.'删除']
menuId = 2027
perms = 'remove'

['VIP管理'.'VIP客户管理'.'按钮权限'.'导入']
menuId = 2028
perms = 'import'

['VIP管理'.'VIP客户管理'.'按钮权限'.'导出']
menuId = 2029
perms = 'export'

#------------------------VIP优惠设置(二级菜单)---------------------------
['VIP管理'.'VIP优惠设置']
menuId = 2030
icon = 'guid'
path = 'vip_offer_settings'

#-----------VIP管理->VIP优惠设置 按钮权限------------
['VIP管理'.'VIP优惠设置'.'按钮权限'.'查询']
menuId = 2031
perms = 'query'

['VIP管理'.'VIP优惠设置'.'按钮权限'.'添加']
menuId = 2032
perms = 'add'

['VIP管理'.'VIP优惠设置'.'按钮权限'.'编辑']
menuId = 2033
perms = 'edit'

['VIP管理'.'VIP优惠设置'.'按钮权限'.'删除']
menuId = 2034
perms = 'remove'

['VIP管理'.'VIP优惠设置'.'按钮权限'.'导入']
menuId = 2035
perms = 'import'

['VIP管理'.'VIP优惠设置'.'按钮权限'.'导出']
menuId = 2036
perms = 'export'

#------------------------流水数据(目录)---------------------------
['流水数据']
menuId = 2037
icon = 'system'
path = 'flow_data'

#------------------------源数据分析(二级菜单)---------------------------
['流水数据'.'源数据分析']
menuId = 2038
icon = 'guid'
path = 'source_data_analysis'

#-----------流水数据->源数据分析 按钮权限------------
['流水数据'.'源数据分析'.'按钮权限'.'查询']
menuId = 2039
perms = 'query'

['流水数据'.'源数据分析'.'按钮权限'.'添加']
menuId = 2040
perms = 'add'

['流水数据'.'源数据分析'.'按钮权限'.'编辑']
menuId = 2041
perms = 'edit'

['流水数据'.'源数据分析'.'按钮权限'.'删除']
menuId = 2042
perms = 'remove'

['流水数据'.'源数据分析'.'按钮权限'.'导入']
menuId = 2043
perms = 'import'

['流水数据'.'源数据分析'.'按钮权限'.'导出']
menuId = 2044
perms = 'export'

#------------------------月数据分析(二级菜单)---------------------------
['流水数据'.'月数据分析']
menuId = 2045
icon = 'guid'
path = 'monthly_data_analysis'

#-----------流水数据->月数据分析 按钮权限------------
['流水数据'.'月数据分析'.'按钮权限'.'查询']
menuId = 2046
perms = 'query'

['流水数据'.'月数据分析'.'按钮权限'.'添加']
menuId = 2047
perms = 'add'

['流水数据'.'月数据分析'.'按钮权限'.'编辑']
menuId = 2048
perms = 'edit'

['流水数据'.'月数据分析'.'按钮权限'.'删除']
menuId = 2049
perms = 'remove'

['流水数据'.'月数据分析'.'按钮权限'.'导入']
menuId = 2050
perms = 'import'

['流水数据'.'月数据分析'.'按钮权限'.'导出']
menuId = 2051
perms = 'export'

#------------------------半年数据分析(二级菜单)---------------------------
['流水数据'.'半年数据分析']
menuId = 2052
icon = 'guid'
path = 'semi_annual_data_analysis'

#-----------流水数据->半年数据分析 按钮权限------------
['流水数据'.'半年数据分析'.'按钮权限'.'查询']
menuId = 2053
perms = 'query'

['流水数据'.'半年数据分析'.'按钮权限'.'添加']
menuId = 2054
perms = 'add'

['流水数据'.'半年数据分析'.'按钮权限'.'编辑']
menuId = 2055
perms = 'edit'

['流水数据'.'半年数据分析'.'按钮权限'.'删除']
menuId = 2056
perms = 'remove'

['流水数据'.'半年数据分析'.'按钮权限'.'导入']
menuId = 2057
perms = 'import'

['流水数据'.'半年数据分析'.'按钮权限'.'导出']
menuId = 2058
perms = 'export'

#------------------------一年数据分析(二级菜单)---------------------------
['流水数据'.'一年数据分析']
menuId = 2059
icon = 'guid'
path = 'one_year_data_analysis'

#-----------流水数据->一年数据分析 按钮权限------------
['流水数据'.'一年数据分析'.'按钮权限'.'查询']
menuId = 2060
perms = 'query'

['流水数据'.'一年数据分析'.'按钮权限'.'添加']
menuId = 2061
perms = 'add'

['流水数据'.'一年数据分析'.'按钮权限'.'编辑']
menuId = 2062
perms = 'edit'

['流水数据'.'一年数据分析'.'按钮权限'.'删除']
menuId = 2063
perms = 'remove'

['流水数据'.'一年数据分析'.'按钮权限'.'导入']
menuId = 2064
perms = 'import'

['流水数据'.'一年数据分析'.'按钮权限'.'导出']
menuId = 2065
perms = 'export'

#------------------------运营管理(目录)---------------------------
['运营管理']
menuId = 2066
icon = 'system'
path = 'operations_management'

#------------------------图片(二级菜单)---------------------------
['运营管理'.'图片']
menuId = 2067
icon = 'guid'
path = 'image'

#-----------运营管理->图片 按钮权限------------
['运营管理'.'图片'.'按钮权限'.'查询']
menuId = 2068
perms = 'query'

['运营管理'.'图片'.'按钮权限'.'添加']
menuId = 2069
perms = 'add'

['运营管理'.'图片'.'按钮权限'.'编辑']
menuId = 2070
perms = 'edit'

['运营管理'.'图片'.'按钮权限'.'删除']
menuId = 2071
perms = 'remove'

['运营管理'.'图片'.'按钮权限'.'导入']
menuId = 2072
perms = 'import'

['运营管理'.'图片'.'按钮权限'.'导出']
menuId = 2073
perms = 'export'

#------------------------文档(二级菜单)---------------------------
['运营管理'.'文档']
menuId = 2074
icon = 'guid'
path = 'documentation'

#-----------运营管理->文档 按钮权限------------
['运营管理'.'文档'.'按钮权限'.'查询']
menuId = 2075
perms = 'query'

['运营管理'.'文档'.'按钮权限'.'添加']
menuId = 2076
perms = 'add'

['运营管理'.'文档'.'按钮权限'.'编辑']
menuId = 2077
perms = 'edit'

['运营管理'.'文档'.'按钮权限'.'删除']
menuId = 2078
perms = 'remove'

['运营管理'.'文档'.'按钮权限'.'导入']
menuId = 2079
perms = 'import'

['运营管理'.'文档'.'按钮权限'.'导出']
menuId = 2080
perms = 'export'

#------------------------签到管理(二级菜单)---------------------------
['运营管理'.'签到管理']
menuId = 2081
icon = 'guid'
path = 'check_in_management'

#-----------运营管理->签到管理 按钮权限------------
['运营管理'.'签到管理'.'按钮权限'.'查询']
menuId = 2082
perms = 'query'

['运营管理'.'签到管理'.'按钮权限'.'添加']
menuId = 2083
perms = 'add'

['运营管理'.'签到管理'.'按钮权限'.'编辑']
menuId = 2084
perms = 'edit'

['运营管理'.'签到管理'.'按钮权限'.'删除']
menuId = 2085
perms = 'remove'

['运营管理'.'签到管理'.'按钮权限'.'导入']
menuId = 2086
perms = 'import'

['运营管理'.'签到管理'.'按钮权限'.'导出']
menuId = 2087
perms = 'export'

#------------------------订单管理(二级菜单)---------------------------
['运营管理'.'订单管理']
menuId = 2088
icon = 'guid'
path = 'order_management'

#-----------运营管理->订单管理 按钮权限------------
['运营管理'.'订单管理'.'按钮权限'.'查询']
menuId = 2089
perms = 'query'

['运营管理'.'订单管理'.'按钮权限'.'添加']
menuId = 2090
perms = 'add'

['运营管理'.'订单管理'.'按钮权限'.'编辑']
menuId = 2091
perms = 'edit'

['运营管理'.'订单管理'.'按钮权限'.'删除']
menuId = 2092
perms = 'remove'

['运营管理'.'订单管理'.'按钮权限'.'导入']
menuId = 2093
perms = 'import'

['运营管理'.'订单管理'.'按钮权限'.'导出']
menuId = 2094
perms = 'export'

