
#------------------------系统(目录)---------------------------
['系统']
menuId = 2000
icon = 'system'
path = 'integral'

#------------------------用户管理(二级菜单)---------------------------
['系统'.'用户管理']
menuId = 2001
icon = 'guid'
path = 'user_management'

#-----------系统->用户管理 按钮权限------------
['系统'.'用户管理'.'按钮权限'.'查询']
menuId = 2002
perms = 'query'

['系统'.'用户管理'.'按钮权限'.'添加']
menuId = 2003
perms = 'add'

['系统'.'用户管理'.'按钮权限'.'编辑']
menuId = 2004
perms = 'edit'

['系统'.'用户管理'.'按钮权限'.'删除']
menuId = 2005
perms = 'remove'

['系统'.'用户管理'.'按钮权限'.'导入']
menuId = 2006
perms = 'import'

['系统'.'用户管理'.'按钮权限'.'导出']
menuId = 2007
perms = 'export'

